### ISSUE TITLE
Group by directory/project for monorepos

### ISSUE THREAD

**Issue by adamjuhasz** [deadpendency/deadpendency#20]
First of all thanks for working on this!

We just installed it on our dual language monorepo (Haskell & Typescript) and the report is a bit hard to read since all projects are included in one giant list. 

Some ideas that would help us out in this situation
- Would be great if we could group the report somehow. For example if multiple directories are detected, then use directory names to group? We can also configure these in the config file too, if that's easier.
- Maybe add a third icon that links to the offending dependency file?

Example showing a mix of JS and Haskell libs

<img width="582" alt="image" src="https://user-images.githubusercontent.com/757940/108387907-ee449c00-71c2-11eb-958f-5f254600aaa9.png">

**Comment by AlistairB** [comment]
Thanks for the feedback!

I think this is a good call, it isn't immediately clear which language or file each package corresponds to, which makes the report harder to visually interpret.

My initial inclination is to start with breaking down each section of `Unhealthy`, `Healthy With Warnings` and `Healthy` down by language headings. This is probably a good low hanging fruit starting point at least. What do you think?

Breaking down by file is interesting, because the same dependency may exist in multiple files (or multiple times in a single file). As such after loading all the dependencies, Deadpendency will deduplicate to get the final list to be checked.

So to include the file information, you would either break down the report by dependency file name and multiple files may have the same dependency report. Or, you would break down by language, but each dependency would link to 1 to many dependency files that included that dependency. I think I prefer the latter as it avoids duplication to keep the report smaller. Any thoughts?

**Comment by adamjuhasz** [comment]
> My initial inclination is to start with breaking down each section of Unhealthy, Healthy With Warnings and Healthy down by language headings. This is probably a good low hanging fruit starting point at least. What do you think?

Sounds good!

> Breaking down by file is interesting, because the same dependency may exist in multiple files (or multiple times in a single file). As such after loading all the dependencies, Deadpendency will deduplicate to get the final list to be checked.

Personally I would prefer duplication as it shows every project that may not "be in compliance", but not sure what the general population prefers. 

> So to include the file information, you would either break down the report by dependency file name and multiple files may have the same dependency report. Or, you would break down by language, but each dependency would link to 1 to many dependency files that included that dependency. I think I prefer the latter as it avoids duplication to keep the report smaller. Any thoughts?

Again my personal preference is towards verbosity and directness since it makes it harder to ignore... but I don't mind scrolling, but probably not as "pretty" as a more concise approach. I would like each language as a heading and then the failure / warning list under it.

This is a super hard combinatorial issue so I don't know if there is an elegant approach 😬

**Comment by AlistairB** [comment]
Thanks. I'll start with the language splitting. 

In terms of making monorepos more manageable, I'll start with linking the related dependency file(s) next to each dependency. That addition seems beneficial to everyone, without introducing duplication or increasing the size of the report. So is a clear win I think.

I can understand why you may want to break down by dependency file, or by directory. I believe a good starting point would be some config setting like `splitByDependencyFile: true`. That would split each section of Unhealthy, Healthy With Warnings and Healthy down by files. I don't imagine having completely separate reports for each dependency file would be good, as mostly you want to ignore the healthy dependencies and just focus on the failing/warning dependencies.

**Comment by adamjuhasz** [comment]
Thanks! Sounds good to me, looking forward to it. Thanks for taking the feedback

Should I close this issue or do you want to keep it open?

**Comment by AlistairB** [comment]
I'll close this and create 3 other issues to track the 3 proposed changes thanks.
