### ISSUE TITLE
Ignore indirect dependencies

### ISSUE THREAD

**Issue by fniessink** [deadpendency/deadpendency#51]
I'd like to ignore indirect dependencies (i.e. dependencies of dependencies that my project uses).

## Why do you want this feature?
When a dependency that my project uses is active, but in turn depends on a dead dependency, that's not my (immediate) problem and not something I can easily solve myself. 

## Acceptance Critera
Provide an option to ignore indirect dependencies. 

Optionally make it possible to specify per dependency whether indirect dependencies should be ignored.

**Comment by AlistairB** [comment]
Thanks for the feedback!

Deadpendency is supposed to ignore direct dependencies. Are you not seeing this behavior? If so that would be a bug and I would love to see an example.

I generally don't see indirect dependency tracking useful, but I'm interested to know if there is some use case where you might want to enable this on a dependency?

The other mechanism available is you can add [arbitrary dependencies in for assessment via config](https://deadpendency.com/docs/config#additional-dependencies). So this might be a good way to track a particularly important indirect dependency?

**Comment by AlistairB** [comment]
Ah I see https://github.com/ICTU/quality-time/commit/102d6e31ef2a8998a91085c7c9aff04a2115b4c7 . Let me do some investigation.

**Comment by AlistairB** [comment]
I think  I misunderstood, the 'extras' feature is more about the dependency configuration rather than additional dependencies. I agree these should be ignored by default. I have made this change in `1.0.6.0`. I think if there is a desire to track these for certain dependencies, I would probably suggest putting them in the deadpendency config.

I'm going to optimistically close, please reopen if you have more concerns. Thanks again!

**Comment by fniessink** [comment]
> Deadpendency is supposed to ignore direct dependencies. Are you not seeing this behavior? If so that would be a bug and I would love to see an example.

No, I'm not seeing that behavior. Deadpendency reports on indirect dependencies too, at least for Python. See this [Deadpendency report](https://github.com/ICTU/quality-time/runs/4843993905). In the linked project, we use pip-compile to generate `requirements.txt` files from `requirements.in` files, so that probably explains why Deadpendency tracks them all, instead of just the dependencies listed in the `requirements.in` files?

> I think I misunderstood, the 'extras' feature is more about the dependency configuration rather than additional dependencies. I agree these should be ignored by default. I have made this change in `1.0.6.0`. I think if there is a desire to track these for certain dependencies, I would probably suggest putting them in the deadpendency config.

I'm sorry, I don't know what the 'extras' feature refers to and what you mean by 'this change'. Also, is release 1.0.6.0 out? Because I don't see any change in Deadpendency's behavior.

Thanks for looking into this!

**Comment by AlistairB** [comment]
Sorry, I may have misunderstood the issue. My understanding was based on https://github.com/ICTU/quality-time/commit/102d6e31ef2a8998a91085c7c9aff04a2115b4c7 that you do not consider `filecache` a direct dependency. `filecache` [only appears](https://github.com/ICTU/quality-time/search?q=filecache) as 'extras' ie. https://github.com/ICTU/quality-time/blob/8d786f6d6dc33e464f0bc42ead53134a82e7ab56/components/server/requirements-dev.txt#L19

My understanding is that the bits between the square brackets, [denote extra features](https://www.python.org/dev/peps/pep-0508/#extras) you can opt in to with a dependency. Previous version of Deadpendency would load these extras, so when it sees `cachecontrol[filecache]` it will load 2 dependencies of `cachecontrol` and `filecache`. However as of `1.0.6.0` I have changed this behaviour to only load 1 dependency of `cachecontrol` (I decided this is a better default). This is change is fully released.

This change appear to be working here https://github.com/deadpendency/quality-time/commit/9f450ccb9f856cebd2466db416fbf3524011404d where I remove that ignore, but `filecache` does not show up as a dependency.

If this is not the problem you are raising, can you give the dependency name you do not expect to be assessed by Deadependency which is?

Deadpendency will also search and load any `/*/requirements*.txt` files by default, so perhaps the issue is as you mention dependencies are coming from this auto load that you don't want?

**Comment by fniessink** [comment]
> If this is not the problem you are raising, can you give the dependency name you do not expect to be assessed by Deadependency which is?

My issue was not specifically about filecache, that was sort of the canary the coal mine that made me realize deadpendency was warning me about indirect dependencies :-). Another example is soupsieve, see below.
 
> Deadpendency will also search and load any `/*/requirements*.txt` files by default (to 1 directory deep), so perhaps the issue is as you mention dependencies are coming from this auto load that you don't want?

I don't think so. We have [configured deadpendency](https://github.com/ICTU/quality-time/blob/master/.github/deadpendency.yaml) as below:

```yaml
additional-dependency-files:
  - type: pip-requirements-txt
    path: components/collector/requirements.in
  - type: pip-requirements-txt
    path: components/collector/requirements-dev.in

  - type: pip-requirements-txt
    path: components/notifier/requirements.in
  - type: pip-requirements-txt
    path: components/notifier/requirements-dev.in

   ...
```

The requirements files for the component are two directories deep, so the auto-loading should not kick in here. The components/collector/requirements.in file contains:

```
aiodns==3.0.0
aiogqlc==3.0.0
aiohttp==3.8.1
beautifulsoup4==4.10.0
cchardet==2.1.7
defusedxml==0.7.1
packaging==21.3
python-dateutil==2.8.2
typing_extensions==4.0.1
```

However, the [deadpendency report ](https://github.com/ICTU/quality-time/runs/4868857938) also lists soupsieve, which is an indirect dependency of beautifulsoup4. I would not expect soupsieve to be included in the deadpendency report. Hope this helps?

**Comment by AlistairB** [comment]
Ah thanks. It appears to be being loaded from https://github.com/ICTU/quality-time/blob/master/docs/requirements-dev.txt#L596 by the auto load process.

I guess the fix for this would be to disabled the auto load? I'd happy to implement this it seems a generally useful feature.

**Comment by fniessink** [comment]
That would be great!

**Comment by AlistairB** [comment]
I have added this feature, see https://deadpendency.com/docs/config#disable-auto-file-load

Using:

```yaml
disable-auto-file-load:
  - python
```

`soupsieve` [is no longer loaded](https://github.com/deadpendency/quality-time/runs/4945044701).

Pondering further, some `exclude-dependency-files` would probably also be useful for cases where you want auto load, but just don't want 1 or 2 files. I could add this now as well if it helps.

**Comment by fniessink** [comment]
Thanks! Works like a charm: https://github.com/ICTU/quality-time/pull/3327/checks?check_run_id=4958663211. 

I can see `exclude-dependency-files` being useful for people who use auto load, but as I've turned auto load off, I won't be needing it.
